
service: utopiabookingservice

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1


functions:
  http:
    handler: src/handler.http
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline

# layers:
#   test:
#     package:
#       artifact: utopiabookingservice.zip

    # layers:
    #   - { Ref: TestLambdaLayer }
